### ISSUE TITLE
Templates Embedded Layout

### ISSUE THREAD

**Issue by LaBoss** [lukencode/FluentEmail#171]
Hello iam using FluentEmail from embedded resources and its Ok, 

But now I need to use the layout tag and I can't

My Code:
   
```
FluentEmail.Core.Email.DefaultRenderer = new FluentEmail.Razor.RazorRenderer(typeof(Sender));

            _email = new FluentEmail.Core.Email();

_email.To(string.Join(",", Data.To))
                                    .BCC(string.Join(",", Data.BCC))
                                    .CC(string.Join(",", Data.CC))
                                    .Subject(Data.Subject)
                                    .UsingTemplateFromEmbedded($"{TemplateResourcesPath}.{Data.Template.ToString()}.cshtml", new
                                           {
                                               Options = _Options,
                                               Entity = Model.ToExpando()
                                           }, GetType().Assembly));

```

**TemplateResourcesPath = ConsoleApp.EmailTemplates.NewAccount.cshtml**

My NewAccount.cshtml
```

@{
    Layout = "_Layout.cshtml";
}
<p>Hi @Model.Entity.Name,</p>`
```

My _Layout.cshtml
```
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title></title>
</head>
<body>
    <h1>xxxxxx</h1>
    <div>@RenderBody</div>
</body>
</html>
```

After running I get the following error
```
`System.InvalidOperationException: Project can not find template with key _Layout.cshtml
 at RazorLight.Generation.RazorSourceGenerator.GenerateCodeAsync(RazorLightProjectItem projectItem)
 at RazorLight.Generation.RazorSourceGenerator.GenerateCodeAsync(String key)
 at RazorLight.Compilation.TemplateFactoryProvider.CreateFactoryAsync(String templateKey)
 at RazorLight.RazorLightEngine.CompileTemplateAsync(String key)
 at RazorLight.TemplateRenderer.RenderLayoutAsync(PageContext context, ViewBufferTextWriter bodyWriter)
 at RazorLight.TemplateRenderer.RenderAsync()
 at RazorLight.RazorLightEngine.RenderTemplateAsync(ITemplatePage templatePage, Object model, Type modelType, TextWriter textWriter, ExpandoObject viewBag)
 at RazorLight.RazorLightEngine.RenderTemplateAsync(ITemplatePage templatePage, Object model, Type modelType, ExpandoObject viewBag)
 at RazorLight.RazorLightEngine.CompileRenderAsync(String key, Object model, Type modelType, ExpandoObject viewBag)
 at CallSite.Target(Closure , CallSite , Object )
 at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
 at FluentEmail.Razor.RazorRenderer.ParseAsync[T](String template, T model, Boolean isHtml)
 at FluentEmail.Razor.RazorRenderer.FluentEmail.Core.Interfaces.ITemplateRenderer.Parse[T](String template, T model, Boolean isHtml)
 at FluentEmail.Core.Email.UsingTemplateFromEmbedded[T](String path, T model, Assembly assembly, Boolean isHtml)
```

I already tried to place the layout with the following paths

- ConsoleApp.EmailTemplates._Layout.cshtml
- EmailTemplates._Layout.cshtml

Someone can help me?
Thank you`

**Comment by bjcull** [comment]
Have a look at https://github.com/lukencode/FluentEmail/blob/6ea1907a34899b0dc0334c5ff88ec3ab221da89f/test/FluentEmail.Razor.Tests/RazorTests.cs#L113
Let me know if it still doesn't work for you.
