### ISSUE TITLE
Cannot send template emails

### ISSUE THREAD

**Issue by zadigus** [lukencode/FluentEmail#222]
I am currently trying to use FluentEmail to send emails from a serverless function. That function is simply a handler that I call from a .net core 3 api. 

In my `Startup` class, I have
```cs
public void ConfigureServices(IServiceCollection services)
{
      services
        .AddControllers()
        .AddNewtonsoftJson();

      services
        [...]
        .AddFluentEmail(Environment.GetEnvironmentVariable("FROM_EMAIL"))
        .AddRazorRenderer()
        .AddSmtpSender(Environment.GetEnvironmentVariable("SMTP_HOST"), int.Parse(Environment.GetEnvironmentVariable("SMTP_PORT")));
}
```
Now, in my handler, if I call
```cs
      await _email
        .To("test@test.test")
        .Subject("Confirmation de commande")
        .Body("This is the email body")
        .SendAsync();
```
then my email is sent properly. If I, however, call
```cs
var template = "Dear @Model.Name, You are totally @Model.Compliment.";

await _email
    .To("test@test.test")
    .Subject("Confirmation de commande")
    .UsingTemplate(template, new { Name = "Luke", Compliment = "awesome" })
    .SendAsync();
```
then my email does not get sent and I also get the following errors:
```
Caught generic Exception: System.InvalidOperationException: Cannot find reference assembly 'Microsoft.AspNetCore.Antiforgery.dll' file for package Microsoft.AspNetCore.Antiforgery
2020-08-24T19:04:29.133916129Z 2020/08/24 19:04:29 stdout:          at Microsoft.Extensions.DependencyModel.Resolution.ReferenceAssemblyPathResolver.TryResolveAssemblyPaths(CompilationLibrary library, List`1 assemblies)
2020-08-24T19:04:29.133969629Z 2020/08/24 19:04:29 stdout:          at Microsoft.Extensions.DependencyModel.Resolution.CompositeCompilationAssemblyResolver.TryResolveAssemblyPaths(CompilationLibrary library, List`1 assemblies)
2020-08-24T19:04:29.134016929Z 2020/08/24 19:04:29 stdout:          at Microsoft.Extensions.DependencyModel.CompilationLibrary.ResolveReferencePaths(ICompilationAssemblyResolver resolver, List`1 assemblies)
2020-08-24T19:04:29.134058129Z 2020/08/24 19:04:29 stdout:          at Microsoft.Extensions.DependencyModel.CompilationLibrary.ResolveReferencePaths()
2020-08-24T19:04:29.134316929Z 2020/08/24 19:04:29 stdout:          at RazorLight.Compilation.DefaultMetadataReferenceManager.<>c.<Resolve>b__6_0(CompilationLibrary library)
2020-08-24T19:04:29.134367129Z 2020/08/24 19:04:29 stdout:          at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
2020-08-24T19:04:29.134413829Z 2020/08/24 19:04:29 stdout:          at RazorLight.Compilation.DefaultMetadataReferenceManager.Resolve(DependencyContext dependencyContext)
2020-08-24T19:04:29.134478529Z 2020/08/24 19:04:29 stdout:          at RazorLight.Compilation.DefaultMetadataReferenceManager.Resolve(Assembly assembly)
2020-08-24T19:04:29.134529729Z 2020/08/24 19:04:29 stdout:          at RazorLight.Compilation.RoslynCompilationService.EnsureOptions()
2020-08-24T19:04:29.134574429Z 2020/08/24 19:04:29 stdout:          at RazorLight.Compilation.RoslynCompilationService.get_ParseOptions()
2020-08-24T19:04:29.134635929Z 2020/08/24 19:04:29 stdout:          at RazorLight.Compilation.RoslynCompilationService.CreateSyntaxTree(SourceText sourceText)
2020-08-24T19:04:29.134907329Z 2020/08/24 19:04:29 stdout:          at RazorLight.Compilation.RoslynCompilationService.CreateCompilation(String compilationContent, String assemblyName)
2020-08-24T19:04:29.134959729Z 2020/08/24 19:04:29 stdout:          at RazorLight.Compilation.RoslynCompilationService.CompileAndEmit(IGeneratedRazorTemplate razorTemplate)
2020-08-24T19:04:29.135007029Z 2020/08/24 19:04:29 stdout:          at RazorLight.Compilation.RoslynCompilationService.CompileAsync(IGeneratedRazorTemplate razorTemplate)
2020-08-24T19:04:29.135049529Z 2020/08/24 19:04:29 stdout:       --- End of stack trace from previous location where exception was thrown ---
2020-08-24T19:04:29.135104329Z 2020/08/24 19:04:29 stdout:          at RazorLight.Compilation.TemplateFactoryProvider.CompileAsync(IGeneratedRazorTemplate razorTemplate)
2020-08-24T19:04:29.135137629Z 2020/08/24 19:04:29 stdout:          at RazorLight.Compilation.TemplateFactoryProvider.CreateFactoryAsync(String templateKey)
2020-08-24T19:04:29.135193529Z 2020/08/24 19:04:29 stdout:          at RazorLight.RazorLightEngine.CompileTemplateAsync(String key)
2020-08-24T19:04:29.135231029Z 2020/08/24 19:04:29 stdout:          at RazorLight.RazorLightEngine.CompileRenderAsync(String key, Object model, Type modelType, ExpandoObject viewBag)
2020-08-24T19:04:29.135296229Z 2020/08/24 19:04:29 stdout:          at CallSite.Target(Closure , CallSite , Object )
2020-08-24T19:04:29.135358629Z 2020/08/24 19:04:29 stdout:          at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
2020-08-24T19:04:29.135410429Z 2020/08/24 19:04:29 stdout:          at FluentEmail.Razor.RazorRenderer.ParseAsync[T](String template, T model, Boolean isHtml)
2020-08-24T19:04:29.135480729Z 2020/08/24 19:04:29 stdout:          at FluentEmail.Razor.RazorRenderer.FluentEmail.Core.Interfaces.ITemplateRenderer.Parse[T](String template, T model, Boolean isHtml)
2020-08-24T19:04:29.135535129Z 2020/08/24 19:04:29 stdout:          at FluentEmail.Core.Email.UsingTemplate[T](String template, T model, Boolean isHtml)
2020-08-24T19:04:29.135587029Z 2020/08/24 19:04:29 stdout:          at Mailing.OrderConfirmation.EmailOrderHandler.Handle(EmailOrderInput oldRow, EmailOrderInput newRow) in /src/app/OrderConfirmation/EmailOrderHandler.cs:line 43
2020-08-24T19:04:29.135631529Z 2020/08/24 19:04:29 stdout:          at CommonLib.Controller.EventControllerBase`2.<>c__DisplayClass3_0.<<DoPost>b__0>d.MoveNext() in /src/CommonLib/Controller/EventControllerBase.cs:line 34
2020-08-24T19:04:29.135690929Z 2020/08/24 19:04:29 stdout:       --- End of stack trace from previous location where exception was thrown ---
```
What am I missing here? I am working with `FluentEmail.Core`, `FluentEmail.Razor`, and `FluentEmail.Smtp` version `v2.8.0` within .Net Core 3.1.

**Comment by zadigus** [comment]
I was expecting the dependencies to be installed automatically with the FluentEmail package. It seems like it's not the case. Manual installation of `Antiforgery` solves the issue.
