### ISSUE TITLE
System.MissingMethodException when using MailKit 3.0.0

### ISSUE THREAD

**Issue by mm-rpodstawa** [lukencode/FluentEmail#296]
I have upgraded MailKit to v3.0.0 and I when I send email get this exception:

System.MissingMethodException: 'Method not found: 'System.Threading.Tasks.Task MailKit.MailTransport.SendAsync(MimeKit.MimeMessage, System.Threading.CancellationToken, MailKit.ITransferProgress)'.'

When I back to MailKit v2.15.0, everything works good again

**Comment by mortenn** [comment]
Related exception I am seeing:
```
System.MissingMethodException: Method not found: 'Void MailKit.MailTransport.Send(MimeKit.MimeMessage, System.Threading.CancellationToken, MailKit.ITransferProgress)'.
   at FluentEmail.MailKitSmtp.MailKitSender.Send(IFluentEmail email, Nullable`1 token)
   at FluentEmail.Core.Email.Send(Nullable`1 token)
```

**Comment by dotnetshadow** [comment]
Any update on this issue?

**Comment by dotnetshadow** [comment]
Is anyone else experiencing this issue?

**Comment by zaha** [comment]
> Is anyone else experiencing this issue?

Yes, same issue here. 
I'm also waiting for this to be resolved, but there seems to be little activity in this project, which is why I'm considering dropping FluentEmail and using MailKit directly. Despite liking the simplicity and syntax, I need a mail library that is well maintained and supported.

**Comment by cchance27** [comment]
Running into this same issue, any word on a workaround besides backing down to mailkit 2.15?

**Comment by mortenn** [comment]
There are only really two solutions to this issue;
1) Wait for a new release
2) Clone the repo and build it yourself

**Comment by Jogai** [comment]
@lukencode Can you elaborate on the status of the project?

**Comment by neozhu** [comment]
please fixed it. :)
