### ISSUE TITLE
SendGrid sender broken on latest SendGrid package release

### ISSUE THREAD

**Issue by jamesfernandes** [lukencode/FluentEmail#309]
[SendGrid v9.26.0](https://github.com/sendgrid/sendgrid-csharp/blob/main/CHANGELOG.md#2022-03-09-version-9260), specifically [PR#1151](https://github.com/sendgrid/sendgrid-csharp/pull/1151). Why didn't they mark it as a breaking change?!

```
System.MissingMethodException
Method not found: 'System.Threading.Tasks.Task`1<System.Collections.Generic.Dictionary`2<System.String,System.Object>> SendGrid.Response.DeserializeResponseBodyAsync(System.Net.Http.HttpContent)'.

System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<System.Collections.Generic.Dictionary`2<System.String,System.Object>> SendGrid.Response.DeserializeResponseBodyAsync(System.Net.Http.HttpContent)'.
   at FluentEmail.SendGrid.SendGridSender.SendAsync(IFluentEmail email, Nullable`1 token)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at FluentEmail.SendGrid.SendGridSender.SendAsync(IFluentEmail email, Nullable`1 token)
   at FluentEmail.Core.Email.SendAsync(Nullable`1 token)
   at Wrkout.Api.Adapters.SendGridMailAdapter.SendMailAsync(Recipient recipient, String subject, String templateFile, Object dataObject, Attachment attachment) in D:\a\1\s\Api\Adapters\SendGridMailAdapter.cs:line 176
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
	#1304	
IMailAdapter.SendSessionConfirmation
```

NOTE: I am working on a PR to address this

**Comment by jamesfernandes** [comment]
Hold on that - looks like [SendGrid is going to roll back the breaking change](https://github.com/sendgrid/sendgrid-csharp/pull/1168).
