### ISSUE TITLE
Package FluentEmail.Liquid conflicts with Elsa

### ISSUE THREAD

**Issue by montoner0** [lukencode/FluentEmail#330]
`FluentEmail.Liquid/3.0.2` nuget package conflicts with `Elsa/2.7.0` package (both use Fluid library). 

As soon as I'm referencing Elsa package in a project, FluentEmail is failing

```
System.Runtime.InteropServices.ExternalException (0xFFFFFFFF): System.TypeLoadException: Could not load type 'Fluid.BaseFluidTemplate`1' from assembly 'Fluid, Version=0.0.0.0, Culture=neutral, PublicKeyToken=51cdb8c1938e4789'.
   at FluentEmail.Liquid.LiquidRenderer.ParseAsync[T](String template, T model, Boolean isHtml)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at FluentEmail.Liquid.LiquidRenderer.ParseAsync[T](String template, T model, Boolean isHtml)
   at FluentEmail.Liquid.LiquidRenderer.Parse[T](String template, T model, Boolean isHtml)
   at FluentEmail.Core.Email.UsingTemplate[T](String template, T model, Boolean isHtml)
```

Probably, version referencing for Fluid.Core (>= 1.0.0) isn't quite correct.

**Comment by florisdipt** [comment]
Crosspost from https://github.com/lukencode/FluentEmail/issues/331

I am currently missing the ability to modify the MemberAccessStrategy which has been merged to master on 21 march 2022 on PR https://github.com/lukencode/FluentEmail/pull/284 but has not been released on Nuget yet.

I would also like a new release for FluentEmail.Liquid
As i would like to use this feature (without directly including the source in my project)

**Comment by hisuwh** [comment]
There is a similar issue with NSwag code generation #339

**Comment by luigisaggese** [comment]
There is any news on this issue? @florisdipt I'm also looking to modify MemberAccessStrategy did you found a solution?
