### ISSUE TITLE
System.ObjectDisposedException when sending email using smtpclient

### ISSUE THREAD

**Issue by wilkovanderveen** [lukencode/FluentEmail#332]
I am getting a `System.ObjectDisposedException` when i try to send an e-mail in a .NET core 6.0 project: 

```
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Mail.SmtpClient'.
   at System.Net.Mail.SmtpClient.SendAsync(MailMessage message, Object userToken)
   at FluentEmail.Smtp.SendMailEx.SendMailExImplAsync(SmtpClient client, MailMessage message, CancellationToken token)
```

I have tried to inject the `smtpclient` _transient_, _scoped_ and as a _singleton_ but niether one of the options fixed this issue.

**Comment by wilkovanderveen** [comment]
Never mind. Was my own mistake. I had to inject a custom _smtpsender_  because of an issue with the current version and I had to use a singleton for the other services.
