### ISSUE TITLE
crashes on macOS - cannot write to disk

### ISSUE THREAD

**Issue by RoseApollo** [lukencode/FluentEmail#362]
crashes on macOS saying that disk is read-only, this happens for both `.send()` and `.SendAsync()`

I am using .net 6.0, and visual studio for Mac to build

```
Unhandled exception. System.IO.IOException: Read-only file system : '/2023-01-17_17-05-04_500'
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at FluentEmail.Core.Defaults.SaveToDiskSender.SaveEmailToDisk(IFluentEmail email)
   at FluentEmail.Core.Defaults.SaveToDiskSender.SendAsync(IFluentEmail email, Nullable`1 token)
   at FluentEmail.Core.Defaults.SaveToDiskSender.Send(IFluentEmail email, Nullable`1 token)
   at FluentEmail.Core.Email.Send(Nullable`1 token)
```

```
FluentEmail.Core.Email
    .From("example@example.com")
    .To("example@example.com")
    .Subject("example")
    .Body("example")
    .Send();
```

**Comment by Willmish** [comment]
same issue here

**Comment by nauticalcoder** [comment]
Has anyone found a resolution for this?  I am also running into this issue.

**Comment by Baunt** [comment]
This message appears when using the DefaultSender. When instantiating the Email class, avoid using the default constructor. Instead, use the alternative constructor: **Email(ITemplateRenderer renderer, ISender sender)**.  

The "Read-only file system" message occurs because DefaultSender attempts to save the email on your machine, but macOS does not permit this action.
