### ISSUE TITLE
Method not found: 'Void Microsoft.Extensions.Caching.Memory.MemoryCacheOptions.set_CompactOnMemoryPressure(Boolean)'.

### ISSUE THREAD

**Issue by isaac2004** [lukencode/FluentEmail#58]
Get this error with below code using SendGrid. Running from Class Library Targeting Dot Net Standard 2.0 with Dot Net Core 2.0 Caller

Here is code

````
       var sender = new SendGridSender(_appConfiguration.Value.SendGridApiKey);
                Email.DefaultSender = sender;
                Email.DefaultRenderer = new RazorRenderer();

                var template = "Dear @Model.Email, Thank you for signing, here is the url @Model.SiteUrl";


                var email = Email.From(_appConfiguration.Value.NoReplyEmail)
                                 .To(model.Email)
                                 .Subject("Welcome to LevinBlog!")
                                 .UsingTemplate(template, new { Email = model.Email, SiteUrl = _appConfiguration.Value.SiteUrl });


`````

And Stack Trace

````
   at RazorLight.Caching.TrackingCompilerCache..ctor(String root)
   at RazorLight.EngineFactory.CreatePhysical(String root, IEngineConfiguration configuration)
   at RazorLight.EngineFactory.CreatePhysical(String root)
   at FluentEmail.Razor.RazorRenderer.Parse[T](String template, T model, Boolean isHtml)
   at FluentEmail.Core.Email.UsingTemplate[T](String template, T model, Boolean isHtml)
   at Service.CommunicationService.SignUpToMailingList(SignUpViewModel model) in Service\CommunicationService.cs:line 83
   at Web.Server.Controllers.Rest.ContactsController.Send(SignUpViewModel model) in Web\Server\Controllers\Rest\ContactsController.cs:line 29
   at Microsoft.AspNetCore.Mvc.Internal.ObjectMethodExecutor.<>c__DisplayClass35_0.<WrapVoidAction>b__0(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__18.MoveNext()


````

**Comment by bjcull** [comment]
Support for .netstandard2.0 has been added in #66. This might fix this issue.
