### ISSUE TITLE
Core ConsoleApp having Runtime Errors compiling Razor Template

### ISSUE THREAD

**Issue by chris31389** [lukencode/FluentEmail#79]
I'm using Visual Studio 2017 15.5 and I have created a Core Console App, added the FluentEmail.Razor project and written this program.cs

``` csharp
class Program
{
    static void Main(string[] args)
    {
        RazorRenderer razorRenderer = new RazorRenderer();
        string template = "Hello @Model.Name. Welcome to @Model.Title repository";
        string result = razorRenderer.ParseAsync(template, new { Name = "Chris", Title = "MyRepo" }).GetAwaiter().GetResult();
        Console.WriteLine(result);
        Console.ReadKey();
    }
}
```
Here is my csproj
``` xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="FluentEmail.Razor" Version="2.3.2" />
  </ItemGroup>
</Project>
```

I got this error:

```
RazorLight.TemplateCompilationException
  HResult=0x80131500
  Message=Failed to compile generated Razor template:
- (3:29) The type or namespace name 'Razor' does not exist in the namespace 'RazorLight' (are you missing an assembly reference?)
- (3:63) Predefined type 'System.String' is not defined or imported
- (3:104) Predefined type 'System.Type' is not defined or imported
- (7:10) The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
- (8:10) The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
- (9:10) The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
- (10:10) The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
- (11:56) The type or namespace name 'TemplatePage<>' does not exist in the namespace 'RazorLight' (are you missing an assembly reference?)
- (11:69) Cannot define a class or member that utilizes 'dynamic' because the compiler required type 'System.Runtime.CompilerServices.DynamicAttribute' cannot be found. Are you missing a reference?
- (11:69) Predefined type 'System.Boolean' is not defined or imported
- (14:66) The return type of an async method must be void, Task or Task<T>
- (14:38) The type or namespace name 'System' could not be found in the global namespace (are you missing an assembly reference?)
- (14:66) 'GeneratedTemplate.ExecuteAsync()': no suitable method found to override
- (16:12) Predefined type 'System.Object' is not defined or imported
- (16:12) The name 'BeginContext' does not exist in the current context
- (16:25) Predefined type 'System.Int32' is not defined or imported
- (16:28) Predefined type 'System.Int32' is not defined or imported
- (16:31) Predefined type 'System.Boolean' is not defined or imported
- (17:12) Predefined type 'System.Object' is not defined or imported
- (17:12) The name 'WriteLiteral' does not exist in the current context
- (17:25) Predefined type 'System.String' is not defined or imported
- (18:12) Predefined type 'System.Object' is not defined or imported
- (18:12) The name 'EndContext' does not exist in the current context
- (19:12) Predefined type 'System.Object' is not defined or imported
- (19:12) The name 'BeginContext' does not exist in the current context
- (19:25) Predefined type 'System.Int32' is not defined or imported
- (19:28) Predefined type 'System.Int32' is not defined or imported
- (19:32) Predefined type 'System.Boolean' is not defined or imported
- (0:1) Predefined type 'System.Object' is not defined or imported
- (0:1) The name 'Write' does not exist in the current context
- (0:7) Predefined type 'System.Object' is not defined or imported
- (0:7) The name 'Model' does not exist in the current context
- (25:12) Predefined type 'System.Object' is not defined or imported
- (25:12) The name 'EndContext' does not exist in the current context
- (26:12) Predefined type 'System.Object' is not defined or imported
- (26:12) The name 'BeginContext' does not exist in the current context
- (26:25) Predefined type 'System.Int32' is not defined or imported
- (26:29) Predefined type 'System.Int32' is not defined or imported
- (26:33) Predefined type 'System.Boolean' is not defined or imported
- (27:12) Predefined type 'System.Object' is not defined or imported
- (27:12) The name 'WriteLiteral' does not exist in the current context
- (27:25) Predefined type 'System.String' is not defined or imported
- (28:12) Predefined type 'System.Object' is not defined or imported
- (28:12) The name 'EndContext' does not exist in the current context
- (29:12) Predefined type 'System.Object' is not defined or imported
- (29:12) The name 'BeginContext' does not exist in the current context
- (29:25) Predefined type 'System.Int32' is not defined or imported
- (29:29) Predefined type 'System.Int32' is not defined or imported
- (29:33) Predefined type 'System.Boolean' is not defined or imported
- (0:25) Predefined type 'System.Object' is not defined or imported
- (0:25) The name 'Write' does not exist in the current context
- (0:31) Predefined type 'System.Object' is not defined or imported
- (0:31) The name 'Model' does not exist in the current context
- (35:12) Predefined type 'System.Object' is not defined or imported
- (35:12) The name 'EndContext' does not exist in the current context
- (36:12) Predefined type 'System.Object' is not defined or imported
- (36:12) The name 'BeginContext' does not exist in the current context
- (36:25) Predefined type 'System.Int32' is not defined or imported
- (36:29) Predefined type 'System.Int32' is not defined or imported
- (36:33) Predefined type 'System.Boolean' is not defined or imported
- (37:12) Predefined type 'System.Object' is not defined or imported
- (37:12) The name 'WriteLiteral' does not exist in the current context
- (37:25) Predefined type 'System.String' is not defined or imported
- (38:12) Predefined type 'System.Object' is not defined or imported
- (38:12) The name 'EndContext' does not exist in the current context
- (14:66) 'GeneratedTemplate.ExecuteAsync()': not all code paths return a value

See CompilationErrors for detailed information

  Source=RazorLight
  StackTrace:
   at RazorLight.Compilation.RoslynCompilationService.CompileAndEmit(GeneratedRazorTemplate razorTemplate)
   at RazorLight.TemplateFactoryProvider.CreateFactory(GeneratedRazorTemplate razorTemplate)
   at RazorLight.TemplateFactoryProvider.<CreateFactoryAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RazorLight.RazorLightEngine.<CompileTemplateAsync>d__10.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RazorLight.RazorLightEngine.<CompileRenderAsync>d__9.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FluentEmail.Razor.RazorRenderer.<ParseAsync>d__0`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ConsoleApp1.Program.Main(String[] args) in D:\Projects\RazorEngineParser5\ConsoleApp1\Program.cs:line 12
```

Any ideas what is causing this?

**Comment by bjcull** [comment]
Hey Chris,
This stumped me for a while! I've discovered a fix that I accidentally already have in my other projects.

Include `<PreserveCompilationContext>true</PreserveCompilationContext>` in your csproj and select "Rebuild Solution" (no idea why a normal build doesn't work).

The original reason I had PreserveCompilationContext was for .net core 1 when precompiled views weren't there by default. For some reason, it fixes this bug.

Anyway, here's the updated csproj:

	<Project Sdk="Microsoft.NET.Sdk">
	  <PropertyGroup>
	    <OutputType>Exe</OutputType>
	    <TargetFramework>netcoreapp2.0</TargetFramework>
	    <PreserveCompilationContext>true</PreserveCompilationContext>
	  </PropertyGroup>
	  <ItemGroup>
	    <PackageReference Include="FluentEmail.Razor" Version="2.3.2" />
	  </ItemGroup>
	</Project>

**Comment by chris31389** [comment]
That really stumped me! Thanks for getting back to me.  I've come across that solution in my searches but It wasn't until I rebuilt the solution that it actually worked.  Thanks 💯

**Comment by chris31389** [comment]
@bjcull I just changed the Target Framework to `net47` and it game me some runtime errors.  I've just submitted pull request #80 that fixed it for me.
